# Generated by Django 3.1.2 on 2020-11-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
