# Generated by Django 3.1.2 on 2020-11-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0002_auto_20201108_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
