# Generated by Django 3.1.2 on 2020-11-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0004_sell_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='image',
            field=models.ImageField(default='', upload_to='img/%y'),
        ),
    ]
