# Generated by Django 3.1.2 on 2020-11-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0005_auto_20201112_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='image',
            field=models.ImageField(default='', upload_to='sell/Images'),
        ),
    ]
