# Generated by Django 3.1.2 on 2020-11-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0008_auto_20201112_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sell/Images/'),
        ),
    ]
