# Generated by Django 3.1.2 on 2020-11-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0010_auto_20201119_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Mechanical Engineer', 'Mechanical Engineer'), ('Civil Engineer', 'Civil Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Information Technology', 'Information Technology')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('2', 'SE'), ('4', 'BE'), ('1', 'FE'), ('3', 'TE')], default='', max_length=50),
        ),
    ]
