# Generated by Django 3.1.2 on 2020-11-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0011_auto_20201119_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_product',
            name='description',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('Fir', 'FE'), ('For', 'BE'), ('Sec', 'SE'), ('Thi', 'TE')], default='', max_length=50),
        ),
    ]
