# Generated by Django 3.1.2 on 2020-11-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0012_auto_20201119_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Civil Engineer', 'Civil Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Information Technology', 'Information Technology'), ('Computer Engineer', 'Computer Engineer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('F.E.', 'FE'), ('B.E.', 'BE'), ('T.E.', 'TE'), ('S.E.', 'SE')], default='', max_length=50),
        ),
    ]
