# Generated by Django 3.1.2 on 2020-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0015_auto_20201119_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='book_type',
            field=models.CharField(choices=[('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Mechanical Engineer', 'Mechanical Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Civil Engineer', 'Civil Engineer'), ('Information Technology', 'Information Technology')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('1', 'FE'), ('4', 'BE'), ('2', 'SE'), ('3', 'TE')], default='', max_length=50),
        ),
    ]
