# Generated by Django 3.1.2 on 2020-11-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0016_auto_20201119_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='book_type',
            field=models.CharField(choices=[('Photocopy', 'Photocopy'), ('Second-Hand', 'Second-Hand'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Civil Engineer', 'Civil Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Information Technology', 'Information Technology')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('BE', 'BE'), ('TE', 'TE')], default='', max_length=50),
        ),
    ]
