# Generated by Django 3.1.2 on 2020-11-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0017_auto_20201119_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='book_type',
            field=models.CharField(choices=[('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Civil Engineer', 'Civil Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Information Technology', 'Information Technology')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('BE', 'BE'), ('TE', 'TE'), ('SE', 'SE'), ('FE', 'FE')], default='', max_length=50),
        ),
    ]
