# Generated by Django 3.1.2 on 2020-11-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0020_auto_20201123_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='book_type',
            field=models.CharField(choices=[('Original', 'Original'), ('Photocopy', 'Photocopy'), ('Second-Hand', 'Second-Hand')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Civil Engineer', 'Civil Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Information Technology', 'Information Technology'), ('Mechanical Engineer', 'Mechanical Engineer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('BE', 'BE'), ('TE', 'TE'), ('SE', 'SE')], default='', max_length=50),
        ),
    ]
