# Generated by Django 3.1.2 on 2020-12-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0022_auto_20201130_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type',
            field=models.CharField(choices=[('Photocopy', 'Photocopy'), ('Second-Hand', 'Second-Hand'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Mechanical Engineer', 'Mechanical Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Civil Engineer', 'Civil Engineer'), ('E&TC Engineer', 'E&TC Engineer'), ('Information Technology', 'Information Technology')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('BE', 'BE'), ('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE')], default='', max_length=50),
        ),
    ]
