# Generated by Django 3.1.2 on 2020-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0023_auto_20201201_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_product',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='sell_product',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sell_product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sell_product',
            name='price',
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_name_a',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_name_b',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_name_c',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_name_d',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_name_e',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_name_f',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_type_a',
            field=models.CharField(choices=[('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_type_b',
            field=models.CharField(choices=[('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_type_c',
            field=models.CharField(choices=[('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_type_d',
            field=models.CharField(choices=[('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_type_e',
            field=models.CharField(choices=[('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='book_type_f',
            field=models.CharField(choices=[('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='bookset_image',
            field=models.ImageField(blank=True, null=True, upload_to='sell/Images'),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='price_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='price_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='price_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='price_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='price_e',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='price_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell_product',
            name='seller_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('E&TC Engineer', 'E&TC Engineer'), ('Civil Engineer', 'Civil Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Information Technology', 'Information Technology'), ('Mechanical Engineer', 'Mechanical Engineer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('SE', 'SE'), ('TE', 'TE'), ('FE', 'FE'), ('BE', 'BE')], default='', max_length=50),
        ),
    ]
