# Generated by Django 3.1.2 on 2020-12-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0024_auto_20201201_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Civil Engineer', 'Civil Engineer'), ('Information Technology', 'Information Technology'), ('Mechanical Engineer', 'Mechanical Engineer'), ('E&TC Engineer', 'E&TC Engineer'), ('Computer Engineer', 'Computer Engineer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('TE', 'TE'), ('FE', 'FE'), ('SE', 'SE'), ('BE', 'BE')], default='', max_length=50),
        ),
    ]
