# Generated by Django 3.1.2 on 2020-12-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0025_auto_20201201_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_product',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_a',
            field=models.CharField(choices=[('Original', 'Original'), ('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_b',
            field=models.CharField(choices=[('Original', 'Original'), ('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_c',
            field=models.CharField(choices=[('Original', 'Original'), ('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_d',
            field=models.CharField(choices=[('Original', 'Original'), ('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_e',
            field=models.CharField(choices=[('Original', 'Original'), ('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_f',
            field=models.CharField(choices=[('Original', 'Original'), ('Second-Hand', 'Second-Hand'), ('Photocopy', 'Photocopy')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('E&TC Engineer', 'E&TC Engineer'), ('Civil Engineer', 'Civil Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Information Technology', 'Information Technology'), ('Mechanical Engineer', 'Mechanical Engineer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='', max_length=50),
        ),
    ]
