# Generated by Django 3.1.2 on 2020-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0027_auto_20201201_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='book_name_a',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_a',
            field=models.CharField(blank=True, choices=[('Photocopy', 'Photocopy'), ('Original', 'Original'), ('Second-Hand', 'Second-Hand')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_b',
            field=models.CharField(choices=[('Photocopy', 'Photocopy'), ('Original', 'Original'), ('Second-Hand', 'Second-Hand')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_c',
            field=models.CharField(choices=[('Photocopy', 'Photocopy'), ('Original', 'Original'), ('Second-Hand', 'Second-Hand')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_d',
            field=models.CharField(choices=[('Photocopy', 'Photocopy'), ('Original', 'Original'), ('Second-Hand', 'Second-Hand')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_e',
            field=models.CharField(choices=[('Photocopy', 'Photocopy'), ('Original', 'Original'), ('Second-Hand', 'Second-Hand')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_f',
            field=models.CharField(choices=[('Photocopy', 'Photocopy'), ('Original', 'Original'), ('Second-Hand', 'Second-Hand')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Civil Engineer', 'Civil Engineer'), ('E&TC Engineer', 'E&TC Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Computer Engineer', 'Computer Engineer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='price_a',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('BE', 'BE'), ('TE', 'TE')], default='', max_length=50),
        ),
    ]
