# Generated by Django 3.1.2 on 2020-12-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0028_auto_20201201_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='book_name_b',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_name_c',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_name_d',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_name_e',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_name_f',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_a',
            field=models.CharField(blank=True, choices=[('Photocopy', 'Photocopy'), ('Second-Hand', 'Second-Hand'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_b',
            field=models.CharField(blank=True, choices=[('Photocopy', 'Photocopy'), ('Second-Hand', 'Second-Hand'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_c',
            field=models.CharField(blank=True, choices=[('Photocopy', 'Photocopy'), ('Second-Hand', 'Second-Hand'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_d',
            field=models.CharField(blank=True, choices=[('Photocopy', 'Photocopy'), ('Second-Hand', 'Second-Hand'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_e',
            field=models.CharField(blank=True, choices=[('Photocopy', 'Photocopy'), ('Second-Hand', 'Second-Hand'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='book_type_f',
            field=models.CharField(blank=True, choices=[('Photocopy', 'Photocopy'), ('Second-Hand', 'Second-Hand'), ('Original', 'Original')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='branch',
            field=models.CharField(choices=[('Civil Engineer', 'Civil Engineer'), ('Information Technology', 'Information Technology'), ('E&TC Engineer', 'E&TC Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Computer Engineer', 'Computer Engineer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='price_b',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='price_c',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='price_d',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='price_e',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='price_f',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sell_product',
            name='year',
            field=models.CharField(choices=[('BE', 'BE'), ('TE', 'TE'), ('FE', 'FE'), ('SE', 'SE')], default='', max_length=50),
        ),
    ]
